### ISSUE TITLE
COCO dataset with Faster R-CNN in Lecture #5

### ISSUE THREAD

**Issue by DeVyacheslav** [learnml-today/object-detection-with-pytorch#24]
Issue with training Faster R-CNN in Google Colab after 1-2 batches (batch_size=3) on COCO dataset:
```
_RuntimeError Traceback (most recent call last)

in () 41 optimizer.zero_grad() 42 ---> 43 loss_dict = model(images, targets) 44 losses = sum(loss for k,loss in loss_dict.items() if k in train_losses) 45 losses.backward()

6 frames

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in call(self, input, **kwargs) 530 result = self._slow_forward(input, *kwargs) 531 else: --> 532 result = self.forward(input, **kwargs) 533 for hook in self._forward_hooks.values(): 534 hook_result = hook(self, input, result)

in forward(self, images, targets, only_proposals) 224 if only_proposals: 225 return proposals, scores --> 226 detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets) 227 228 losses = {}

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in call(self, input, **kwargs) 530 result = self._slow_forward(input, *kwargs) 531 else: --> 532 result = self.forward(input, **kwargs) 533 for hook in self._forward_hooks.values(): 534 hook_result = hook(self, input, result)

in forward(self, features, proposals, image_shapes, targets) 193 result, losses = [], {} 194 if self.training: --> 195 loss_classifier, loss_box_reg = fastrcnn_loss(class_logits, box_regression, labels, regression_targets) 196 losses = dict(loss_classifier=loss_classifier, loss_box_reg=loss_box_reg) 197 else:

in fastrcnn_loss(class_logits, box_regression, labels, regression_targets, alpha) 18 labels = torch.cat(labels, dim=0) 19 regression_targets = torch.cat(regression_targets, dim=0) ---> 20 classification_loss = F.cross_entropy(class_logits, labels.long()) 21 # get indices that correspond to the regression targets for 22 # the corresponding ground truth labels, to be used with

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction) 2019 if size_average is not None or reduce is not None: 2020 reduction = _Reduction.legacy_get_string(size_average, reduce) -> 2021 return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction) 2022 2023

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction) 1836 .format(input.size(0), target.size(0))) 1837 if dim == 2: -> 1838 ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index) 1839 elif dim == 4: 1840 ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110_
```
Sometimes training stopped with error:
```
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-31-45a817193b4c> in <module>()
     25     state = torch.load(path_load)
     26     model.load_state_dict(state)
---> 27 model = model.to(device)
     28 
     29 optimizer = optim.SGD(model.parameters(), momentum=0.9, lr=5e-4)

6 frames

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in to(self, *args, **kwargs)
    423             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    424 
--> 425         return self._apply(convert)
    426 
    427     def register_backward_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    199     def _apply(self, fn):
    200         for module in self.children():
--> 201             module._apply(fn)
    202 
    203         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    199     def _apply(self, fn):
    200         for module in self.children():
--> 201             module._apply(fn)
    202 
    203         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    199     def _apply(self, fn):
    200         for module in self.children():
--> 201             module._apply(fn)
    202 
    203         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    199     def _apply(self, fn):
    200         for module in self.children():
--> 201             module._apply(fn)
    202 
    203         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    221                 # `with torch.no_grad():`
    222                 with torch.no_grad():
--> 223                     param_applied = fn(param)
    224                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    225                 if should_use_set_data:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
    421 
    422         def convert(t):
--> 423             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    424 
    425         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered
```
Also the same issue arises when training is failed and after running the following code:
```
import torch
print(torch.rand(1, device="cuda"))
```
Any suggestions?

**Comment by creotiv** [comment]
Seems like container issue, try to terminate all sessions in "Runtime->Manage sessions" and then reallocate new instance. if will not help try to reinstall pytorch==1.2 (but i just tested on 1.4 and didnt see a problem)

**Comment by DeVyacheslav** [comment]
The issue was in target data, overall Coco dataset contains 81 classes, so I created model with num_classes=81, BUT the maximum id in target is 91, so when the model tries to predict class id > 81 - it fails. Now I fixed the model and started training.
